---
# defaults file for niccli

# To update - go here, download the latest Linux bundle, and note the URL+checksum:
#   https://www.broadcom.com/support/download-search?pg=&pf=Ethernet+Connectivity,+Switching,+and+PHYs&pn=&pa=&po=&dk=niccli&pl=&l=false
# Potential patterns include:
#   - 'Broadcom BCM5760X Software Package'
#   - 'Broadcom NetXtreme-E Linux Installer'
#   - 'NetXtreme-E Linux Driver'
#
# NOTE/warning: URL patterns are not consistent enough for templating to make much sense; provide/set the full URL at once. See above for discovery process.
niccli_url: 'https://docs.broadcom.com/docs-and-downloads/ethernet-network-adapters/NXE/Thor2/GCA1/bcm5760x_230.2.52.0a.zip'

# 'niccli_sum' deliberately is *not* defaulted with the URL. if users want to change the URL... this should not require the checksum be corrected/emptied
# this should act as opt-in validation, not a requirement

# install the CLI and driver by default, may opt out
niccli_driver: true
niccli_wanted: true

niccli_requirements:  # mapped by 'ansible_os_family' fact
  common:
    - dkms
    - pciutils
    - unzip
  Debian:
    - build-essential
    - ibverbs-providers
    - ibverbs-utils
    - libaio-dev
    - libibverbs1
    - libibverbs-dev
    - libstdc++-12-dev
    - libelf-dev
    - libibumad-dev
    - librdmacm-dev
    - linux-headers-generic
    - "linux-headers-{{ ansible_kernel }}"
    - "linux-modules-extra-{{ ansible_kernel }}"
    - rdmacm-utils
  RedHat:
    - '@Development Tools'  # group notation (@...) requires quoting
    - kernel-headers
    - kernel-devel-matched
    - kernel-modules-extra
    - libstdc++-devel
    - libaio-devel
    - libibumad
    - libibverbs
    - libibverbs-utils
    - elfutils-libelf-devel
    - librdmacm-utils
