---
# defaults file for niccli

# To update - go here, download the latest Linux bundle, and note the URL+checksum:
#   https://www.broadcom.com/support/download-search?pg=&pf=Ethernet+Connectivity,+Switching,+and+PHYs&pn=&pa=&po=&dk=niccli&pl=&l=false
# Potential patterns include:
#   - 'Broadcom BCM5760X Software Package'
#   - 'Broadcom NetXtreme-E Linux Installer'
#   - 'NetXtreme-E Linux Driver'
#
# NOTE/Warning: Patterns in URLs have not been consistent enough for templating to make [much] sense. Directories change along with releases.
niccli_url: 'https://docs.broadcom.com/docs-and-downloads/ethernet-network-adapters/NXE/Thor2/GCA2/bcm5760x_231.2.63.0a.zip'

# 'niccli_sum' deliberately is *not* defaulted with the URL.
# if users want to change the link... they should not be required to correct or empty the checksum. this should act as opt-in validation, not a requirement.

# install the CLI and driver by default, may opt out
niccli_driver: true
niccli_wanted: true
