---
# defaults file for niccli

# To update - go here, download the latest Linux bundle, and note the URL+checksum:
#   https://www.broadcom.com/support/download-search?pg=&pf=Ethernet+Connectivity,+Switching,+and+PHYs&pn=&pa=&po=&dk=niccli&pl=&l=false
# Potential patterns include:
#   - 'Broadcom BCM5760X Software Package'
#   - 'Broadcom NetXtreme-E Linux Installer'
#   - 'NetXtreme-E Linux Driver'
#
# NOTE/warning: URL patterns are not consistent enough for templating to make much sense; provide/set the full URL at once. See above for discovery process.
niccli_url: 'https://docs.broadcom.com/docs-and-downloads/ethernet-network-adapters/NXE/Thor2/GCA1/bcm5760x_230.2.52.0a.zip'
niccli_sum: 'sha256:1dd2a7c6978c978febfc08ef2f416b2745573848d45700737d4b1405d8e1ac35'

# install the CLI and driver by default, may opt out
niccli_driver: true
niccli_wanted: true
