---
- name: Manage 'amdgpu-install'
  hosts: default
  environment:
    LANG: C  # some tasks process std{out,err}, aim for consistency
    # may be superfluous for your environment; mapped through Packer HCL with 'ansible_env_vars'
    http_proxy: "{{ lookup('ansible.builtin.env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('ansible.builtin.env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('ansible.builtin.env', 'no_proxy') | default(omit) }}"
  roles:
    - { role: amdgpu_install }
