---
# vim: ft=yaml.ansible
# yamllint disable rule:line-length
- name: Build 'packer-rocm'
  hosts: localhost
  gather_facts: false
  vars:
    packer_rocm_dir: "{{ (playbook_dir, '..') | path_join }}"
    packer_maas_dir: "{{ (packer_rocm_dir, 'packer-maas') | path_join }}"
    packer_vars:  # override 'packer build' if any of these are defined (with '-e var=value', inventory, or host/group vars)
      - headless
      - rocm_extras
      - rocm_kernel
      - rocm_releases
      - rocm_builder_disk
      - rocm_builder_cpus
      - rocm_builder_memory
      - rocm_installed
      - niccli_wanted
      - niccli_driver
      - niccli_url
      - niccli_sum
  tasks:
    - name: Preparation
      tags: ['prep']
      block:
        - name: "Manage clone for 'packer-maas' under ADA"
          ansible.builtin.git:
            repo: "https://github.com/canonical/packer-maas.git"
            dest: "{{ packer_maas_dir }}"
            version: "{{ packer_maas_tag | default('9046979a9e92bb0303ef47da180b0af29f03332f') }}"  # current latest ('v1.2.0') lacks several relevant fixes, default to known commit

        - name: "Synchronize 'packer-maas' with ADA 'packer-rocm' assets"
          ansible.posix.synchronize:
            src: "{{ packer_rocm_dir }}/"  # trailing '/' on source is significant; copying *contents* of the dir
            dest: "{{ packer_maas_dir }}"
            rsync_opts:
              - "--exclude='*.md'"
              - "--exclude='NOTICE'"
              - "--exclude='LICENSE'"
              - "--exclude='packer-maas'"

        - name: "Ensure Packer plugins are installed"
          ansible.builtin.command: "packer init {{ (packer_maas_dir, 'ubuntu') | path_join }}"
          changed_when: false

    - name: Build
      ansible.builtin.command:
        cmd: >
          packer build
          {% for _var in packer_vars if vars[_var] is defined %}
          {{ '-var ' + _var + '=' + vars[_var] }}
          {% endfor %}
          -only=qemu.rocm .
        chdir: "{{ build_dir }}"
        creates: "{{ (build_dir, 'ubuntu-rocm.dd.gz') | path_join }}"  # avoid overwriting - require delete
      vars:
        build_dir: "{{ (packer_maas_dir, 'ubuntu') | path_join }}"
      environment:
        PACKER_LOG: '1'  # wanted as str
