---
# Copyright (c) 2024 Advanced Micro Devices, Inc. All rights reserved.
# yamllint disable rule:line-length
- name: "ROCm {{ rocm_release + '-' + rocm_release_build }}"  # expected from Packer or extra-vars
  hosts: default
  become: true
  environment:  # may be superfluous; mapped through Packer HCL with 'ansible_env_vars'
    http_proxy: "{{ lookup('ansible.builtin.env', 'http_proxy', default=Undefined) }}"
    https_proxy: "{{ lookup('ansible.builtin.env', 'https_proxy', default=Undefined) }}"
    no_proxy: "{{ lookup('ansible.builtin.env', 'no_proxy', default=Undefined) }}"
  vars:
    rocm_amdgpu_pkg:
      debian: "https://repo.radeon.com/amdgpu-install/{{ rocm_release }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/amdgpu-install_{{ rocm_release_build }}_all.deb"
      redhat: "https://repo.radeon.com/amdgpu-install/{{ rocm_release }}/rhel/{{ ansible_distribution_version }}/amdgpu-install_{{ rocm_release_build }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
    rocm_reqs:
      common:
        - dkms
      debian:
        - "linux-headers-{{ ansible_kernel }}"
        - "linux-modules-extra-{{ ansible_kernel }}"
      redhat:
        - "kernel-headers"
        - "kernel-devel-matched"
        - "kernel-modules-extra"
  tasks:
    - name: Install Requirements
      ansible.builtin.package:
        name: "{{ rocm_reqs['common'] + rocm_reqs[(ansible_os_family | lower)] }}"
        state: present
        update_cache: true  # passed to the modules for either 'apt' or 'dnf'; supported by either

    - name: Install 'amdgpu-install'
      ansible.builtin.package:  # module/backing package managers are inconsistent with URL handling as 'name'
        name: "{{ rocm_amdgpu_pkg['redhat'] if ansible_os_family in ['RedHat'] else omit }}"
        deb: "{{ rocm_amdgpu_pkg['debian'] if ansible_os_family in ['Debian'] else omit }}"

    - name: "Install {{ _pkgs }}"
      ansible.builtin.package:
        name: "{{ _pkgs }}"
        state: present
        update_cache: true
      vars:
        # serialized through 'extra_arguments' with Packer/the Ansible plugin
        # use 'split' filter to return this comma-separated string to a list [if applicable]
        _pkgs: "{{ amdgpu_install | split(',') }}"  # default: '["amdgpu-dkms", "rocm"]', see 'ubuntu-rocm.variables.pkr.hcl'
# vim: ft=yaml.ansible
