---
name: Lint 'packer-rocm'

on:
  push:
    paths:
      - 'packer-rocm/**'
  pull_request:
    paths:
      - 'packer-rocm/**'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Cache Ansible Collections
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.ansible/collections
          key: ansible-collections-${{ hashFiles('packer-rocm/requirements.yml') }}

      - name: Install Ansible and Collections
        run: |
          pip install --no-compile ansible-core ansible-lint
          ansible-galaxy collection install -r packer-rocm/requirements.yml

      - name: ansible-lint
        run: |
          ansible-lint --profile production --parseable --nocolor --exclude='packer-rocm/packer-maas/' packer-rocm/

# Not yet validating HCL, challenge:
# Many out-of-place references to 'packer-maas' until playbook-run; Packer is strict
#
#      - name: Setup `packer`
#        uses: hashicorp/setup-packer@v3.1.0
#        id: setup
#        with:
#          version: "latest"
